<a href="https://colab.research.google.com/github/YomnaAhmed97/Simple-code-examples/blob/main/Sudoku_Solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
  grid = [[5,3,0,0,7,0,0,0,0],
         [6,0,0,1,9,5,0,0,0],
         [0,9,8,0,0,0,0,6,0],
         [8,0,0,0,6,0,0,0,3],
         [4,0,0,8,0,3,0,0,1],
         [7,0,0,0,2,0,0,0,6],
         [0,6,0,0,0,0,2,8,0],
         [0,0,0,0,1,9,0,0,5],
         [0,0,0,0,0,0,0,0,0]]

In [3]:
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 0 1 9 0 0 5]
 [0 0 0 0 0 0 0 0 0]]


In [4]:
def possible_solns(row,col,num):
  global grid
 
  #Is number appers in a given row?
  for i in range(0,9):
    if grid[row][i]==num:
     return False
  #Is number appers in a given column?
  for i in range(0,9):
    if grid [i][col]==num:
      return False
  #Is number appers in a given square?
  x= (col // 3) * 3
  y= (row // 3) * 3
  for i in range(0,3):
    for j in range(0,3):
      if grid[y+i][x+j]==num:
       return False
  return True

In [10]:
def solve():
  global grid
  for row in range(0,9):
    for col in range(0,9):
      if grid[row][col]==0:
        for num in range(1,10):
          if possible_solns(row,col,num):
            grid[row][col]=num
            solve()
            #if stuck
            grid[row][col] = 0
        return
    print(np.matrix(grid))
    input('More possible solutions')


In [12]:
solve()

[[5 3 1 2 7 6 4 9 8]
 [6 2 4 1 9 5 3 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 0 1 9 0 0 5]
 [0 0 0 0 0 0 0 0 0]]
More possible solutions
[[5 3 1 2 7 6 4 9 8]
 [6 2 4 1 9 5 3 7 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 0 1 9 0 0 5]
 [0 0 0 0 0 0 0 0 0]]
More possible solutions
